services:
  db:
    image: postgres:16-alpine
    container_name: scr-db-1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  db-api:
    build: ./database/
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: mydb
      PG_USER: myuser
      PG_PASS: mypassword
    ports:
      - "8000:8000"

  db-update:
    build: ./database/
    depends_on:
      - db-api
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: mydb
      PG_USER: myuser
      PG_PASS: mypassword
    entrypoint: ""
    command: >
      sh -c "while true; do
              python update_db.py || echo 'ERROR - update_db.py failed, will retry in 10m';
              sleep 600;
            done"

  streamlit-app:
    build: ./dashboard/
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false

volumes:
  db-data: