services:
  db:
    image: postgres:16-alpine
    container_name: scr-db-1
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  db-api:
    build: ./database/
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: mydb
      PG_USER: myuser
      PG_PASS: mypassword
    ports:
      - "8000:8000"

volumes:
  db-data: